// Periodic table: element symbols and ground-state electron configurations for Z = 1..118.
//
// Configurations are generated by the Madelung (n+l, then n) Aufbau ordering, with the
// experimentally-known neutral-atom anomalies (Cr, Cu, the 4d row, the lanthanide/actinide d/f
// crossovers, Pt, Au, ...) applied as overrides. These feed the radial Kohn-Sham solver
// (radialKohnSham.js) as { n, l, occupancy } subshell lists, so any element can be configured and
// solved. The configuration data is standard reference chemistry, not a fit.

export const ELEMENT_SYMBOLS = Object.freeze([
  'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
  'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
  'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn',
  'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr',
  'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn',
  'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd',
  'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb',
  'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg',
  'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th',
  'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm',
  'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds',
  'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'
]);

// Standard atomic weights (u), Z = 1..118; for unstable elements the most-stable-isotope mass
// number. Used to turn a derived number density into a mass density.
export const ATOMIC_MASS_U = Object.freeze([
  1.008, 4.0026, 6.94, 9.0122, 10.81, 12.011, 14.007, 15.999, 18.998, 20.180,
  22.990, 24.305, 26.982, 28.085, 30.974, 32.06, 35.45, 39.948, 39.098, 40.078,
  44.956, 47.867, 50.942, 51.996, 54.938, 55.845, 58.933, 58.693, 63.546, 65.38,
  69.723, 72.630, 74.922, 78.971, 79.904, 83.798, 85.468, 87.62, 88.906, 91.224,
  92.906, 95.95, 98, 101.07, 102.91, 106.42, 107.87, 112.41, 114.82, 118.71,
  121.76, 127.60, 126.90, 131.29, 132.91, 137.33, 138.91, 140.12, 140.91, 144.24,
  145, 150.36, 151.96, 157.25, 158.93, 162.50, 164.93, 167.26, 168.93, 173.05,
  174.97, 178.49, 180.95, 183.84, 186.21, 190.23, 192.22, 195.08, 196.97, 200.59,
  204.38, 207.2, 208.98, 209, 210, 222, 223, 226, 227, 232.04,
  231.04, 238.03, 237, 244, 243, 247, 247, 251, 252, 257,
  258, 259, 266, 267, 268, 269, 270, 269, 278, 281,
  282, 285, 286, 289, 290, 293, 294, 294
]);

const ATOMIC_MASS_UNIT_KG = 1.66053906660e-27;

/** Atomic mass (kg) for atomic number Z. */
export function atomicMassKg(Z) {
  return ATOMIC_MASS_U[Z - 1] * ATOMIC_MASS_UNIT_KG;
}

export const SUBSHELL_CAPACITY = Object.freeze({ 0: 2, 1: 6, 2: 10, 3: 14 });
const L_LABEL = ['s', 'p', 'd', 'f'];

/** Symbol for atomic number Z (1-based), or null if out of range. */
export function symbolForZ(Z) {
  return ELEMENT_SYMBOLS[Z - 1] ?? null;
}

/** Atomic number for an element symbol, or null. */
export function zForSymbol(symbol) {
  const idx = ELEMENT_SYMBOLS.indexOf(symbol);
  return idx >= 0 ? idx + 1 : null;
}

// Madelung subshell ordering: increasing (n + l), ties broken by increasing n.
function madelungOrder() {
  const shells = [];
  for (let n = 1; n <= 8; n += 1) {
    for (let l = 0; l < n && l <= 3; l += 1) shells.push({ n, l });
  }
  shells.sort((a, b) => (a.n + a.l) - (b.n + b.l) || a.n - b.n);
  return shells;
}
const MADELUNG = madelungOrder();

// Neutral-atom ground-state anomalies vs strict Madelung filling. Each entry is the FULL subshell
// occupancy list past the preceding noble-gas core handled implicitly by filling order — but to
// keep it unambiguous we encode the deviating valence subshells as absolute {n,l,occupancy} and
// merge them over the Madelung result. (Standard reference configurations.)
const ANOMALIES = {
  24: { '3,2': 5, '4,0': 1 }, // Cr [Ar]3d5 4s1
  29: { '3,2': 10, '4,0': 1 }, // Cu [Ar]3d10 4s1
  41: { '4,2': 4, '5,0': 1 }, // Nb [Kr]4d4 5s1
  42: { '4,2': 5, '5,0': 1 }, // Mo [Kr]4d5 5s1
  44: { '4,2': 7, '5,0': 1 }, // Ru [Kr]4d7 5s1
  45: { '4,2': 8, '5,0': 1 }, // Rh [Kr]4d8 5s1
  46: { '4,2': 10, '5,0': 0 }, // Pd [Kr]4d10 (5s0)
  47: { '4,2': 10, '5,0': 1 }, // Ag [Kr]4d10 5s1
  57: { '4,3': 0, '5,2': 1, '6,0': 2 }, // La [Xe]5d1 6s2
  58: { '4,3': 1, '5,2': 1, '6,0': 2 }, // Ce [Xe]4f1 5d1 6s2
  64: { '4,3': 7, '5,2': 1, '6,0': 2 }, // Gd [Xe]4f7 5d1 6s2
  78: { '4,3': 14, '5,2': 9, '6,0': 1 }, // Pt [Xe]4f14 5d9 6s1
  79: { '4,3': 14, '5,2': 10, '6,0': 1 }, // Au [Xe]4f14 5d10 6s1
  89: { '5,3': 0, '6,2': 1, '7,0': 2 }, // Ac [Rn]6d1 7s2
  90: { '5,3': 0, '6,2': 2, '7,0': 2 }, // Th [Rn]6d2 7s2
  91: { '5,3': 2, '6,2': 1, '7,0': 2 }, // Pa [Rn]5f2 6d1 7s2
  92: { '5,3': 3, '6,2': 1, '7,0': 2 }, // U  [Rn]5f3 6d1 7s2
  93: { '5,3': 4, '6,2': 1, '7,0': 2 }, // Np [Rn]5f4 6d1 7s2
  96: { '5,3': 7, '6,2': 1, '7,0': 2 } // Cm [Rn]5f7 6d1 7s2
};

/**
 * Ground-state electron configuration for atomic number Z as an ordered list of
 * { n, l, occupancy } subshells (only non-empty subshells). Madelung filling with the standard
 * neutral-atom anomalies applied. Ordered by (n, l) for stable, comparable output.
 */
export function electronConfiguration(Z, { applyAnomalies = true } = {}) {
  if (!Number.isInteger(Z) || Z < 1 || Z > 118) throw new RangeError(`Z out of range: ${Z}`);
  const occ = new Map(); // "n,l" -> occupancy
  let remaining = Z;
  for (const { n, l } of MADELUNG) {
    if (remaining <= 0) break;
    const fill = Math.min(SUBSHELL_CAPACITY[l], remaining);
    occ.set(`${n},${l}`, fill);
    remaining -= fill;
  }
  if (applyAnomalies && ANOMALIES[Z]) {
    for (const [key, value] of Object.entries(ANOMALIES[Z])) {
      if (value === 0) occ.delete(key);
      else occ.set(key, value);
    }
  }
  const config = [];
  for (const [key, occupancy] of occ) {
    if (occupancy <= 0) continue;
    const [n, l] = key.split(',').map(Number);
    config.push({ n, l, occupancy });
  }
  config.sort((a, b) => a.n - b.n || a.l - b.l);
  return config;
}

/** Human-readable spectroscopic string, e.g. "1s2 2s2 2p6 3s2 3p6 4s2 3d6" (filling order). */
export function configurationString(Z, options) {
  const config = electronConfiguration(Z, options);
  // Present in Madelung filling order for readability.
  const order = new Map(MADELUNG.map((s, i) => [`${s.n},${s.l}`, i]));
  return [...config]
    .sort((a, b) => (order.get(`${a.n},${a.l}`) ?? 99) - (order.get(`${b.n},${b.l}`) ?? 99))
    .map((s) => `${s.n}${L_LABEL[s.l]}${s.occupancy}`)
    .join(' ');
}

/** Total electron count of a configuration (sanity: equals Z). */
export function configurationElectronCount(config) {
  return config.reduce((sum, s) => sum + s.occupancy, 0);
}

/**
 * Spin-resolved configuration applying Hund's first rule per subshell: a subshell of capacity
 * 2(2l+1) fills its 2l+1 spin-up slots singly first, then pairs with spin-down. Returns
 * { n, l, occUp, occDown } subshells; the total spin moment is Σ(occUp − occDown). (Per-subshell
 * Hund is the standard atomic-LSDA filling; e.g. Fe 3d6 → 5↑ 1↓, moment 4.)
 */
export function spinElectronConfiguration(Z, options) {
  return electronConfiguration(Z, options).map(({ n, l, occupancy }) => {
    const halfCapacity = 2 * l + 1;
    const occUp = Math.min(occupancy, halfCapacity);
    const occDown = occupancy - occUp;
    return { n, l, occUp, occDown };
  });
}

/** Net spin (Σ(↑−↓)/... here Σ(↑−↓), i.e. 2S) of the ground-state configuration. */
export function unpairedElectronCount(Z, options) {
  return spinElectronConfiguration(Z, options).reduce((sum, s) => sum + (s.occUp - s.occDown), 0);
}

/**
 * Free-electron valence count: the s+p electrons of the outermost principal shell — the
 * nearly-free conduction electrons of a simple metal. (Partially filled d/f shells of an inner
 * principal number are treated as core here; that is the free-electron model's limitation for
 * transition/rare-earth metals, flagged by the closure rather than hidden.)
 */
export function valenceElectronCount(Z, options) {
  const config = electronConfiguration(Z, options);
  const maxN = config.reduce((m, s) => Math.max(m, s.n), 0);
  return config
    .filter((s) => s.n === maxN && (s.l === 0 || s.l === 1))
    .reduce((sum, s) => sum + s.occupancy, 0);
}
