// Periodic table: element symbols and ground-state electron configurations for Z = 1..118.
//
// Configurations are generated by the Madelung (n+l, then n) Aufbau ordering, with the
// experimentally-known neutral-atom anomalies (Cr, Cu, the 4d row, the lanthanide/actinide d/f
// crossovers, Pt, Au, ...) applied as overrides. These feed the radial Kohn-Sham solver
// (radialKohnSham.js) as { n, l, occupancy } subshell lists, so any element can be configured and
// solved. The configuration data is standard reference chemistry, not a fit.

export const ELEMENT_SYMBOLS = Object.freeze([
  'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
  'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
  'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn',
  'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr',
  'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn',
  'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd',
  'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb',
  'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg',
  'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th',
  'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm',
  'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds',
  'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'
]);

export const SUBSHELL_CAPACITY = Object.freeze({ 0: 2, 1: 6, 2: 10, 3: 14 });
const L_LABEL = ['s', 'p', 'd', 'f'];

/** Symbol for atomic number Z (1-based), or null if out of range. */
export function symbolForZ(Z) {
  return ELEMENT_SYMBOLS[Z - 1] ?? null;
}

/** Atomic number for an element symbol, or null. */
export function zForSymbol(symbol) {
  const idx = ELEMENT_SYMBOLS.indexOf(symbol);
  return idx >= 0 ? idx + 1 : null;
}

// Madelung subshell ordering: increasing (n + l), ties broken by increasing n.
function madelungOrder() {
  const shells = [];
  for (let n = 1; n <= 8; n += 1) {
    for (let l = 0; l < n && l <= 3; l += 1) shells.push({ n, l });
  }
  shells.sort((a, b) => (a.n + a.l) - (b.n + b.l) || a.n - b.n);
  return shells;
}
const MADELUNG = madelungOrder();

// Neutral-atom ground-state anomalies vs strict Madelung filling. Each entry is the FULL subshell
// occupancy list past the preceding noble-gas core handled implicitly by filling order — but to
// keep it unambiguous we encode the deviating valence subshells as absolute {n,l,occupancy} and
// merge them over the Madelung result. (Standard reference configurations.)
const ANOMALIES = {
  24: { '3,2': 5, '4,0': 1 }, // Cr [Ar]3d5 4s1
  29: { '3,2': 10, '4,0': 1 }, // Cu [Ar]3d10 4s1
  41: { '4,2': 4, '5,0': 1 }, // Nb [Kr]4d4 5s1
  42: { '4,2': 5, '5,0': 1 }, // Mo [Kr]4d5 5s1
  44: { '4,2': 7, '5,0': 1 }, // Ru [Kr]4d7 5s1
  45: { '4,2': 8, '5,0': 1 }, // Rh [Kr]4d8 5s1
  46: { '4,2': 10, '5,0': 0 }, // Pd [Kr]4d10 (5s0)
  47: { '4,2': 10, '5,0': 1 }, // Ag [Kr]4d10 5s1
  57: { '4,3': 0, '5,2': 1, '6,0': 2 }, // La [Xe]5d1 6s2
  58: { '4,3': 1, '5,2': 1, '6,0': 2 }, // Ce [Xe]4f1 5d1 6s2
  64: { '4,3': 7, '5,2': 1, '6,0': 2 }, // Gd [Xe]4f7 5d1 6s2
  78: { '4,3': 14, '5,2': 9, '6,0': 1 }, // Pt [Xe]4f14 5d9 6s1
  79: { '4,3': 14, '5,2': 10, '6,0': 1 }, // Au [Xe]4f14 5d10 6s1
  89: { '5,3': 0, '6,2': 1, '7,0': 2 }, // Ac [Rn]6d1 7s2
  90: { '5,3': 0, '6,2': 2, '7,0': 2 }, // Th [Rn]6d2 7s2
  91: { '5,3': 2, '6,2': 1, '7,0': 2 }, // Pa [Rn]5f2 6d1 7s2
  92: { '5,3': 3, '6,2': 1, '7,0': 2 }, // U  [Rn]5f3 6d1 7s2
  93: { '5,3': 4, '6,2': 1, '7,0': 2 }, // Np [Rn]5f4 6d1 7s2
  96: { '5,3': 7, '6,2': 1, '7,0': 2 } // Cm [Rn]5f7 6d1 7s2
};

/**
 * Ground-state electron configuration for atomic number Z as an ordered list of
 * { n, l, occupancy } subshells (only non-empty subshells). Madelung filling with the standard
 * neutral-atom anomalies applied. Ordered by (n, l) for stable, comparable output.
 */
export function electronConfiguration(Z, { applyAnomalies = true } = {}) {
  if (!Number.isInteger(Z) || Z < 1 || Z > 118) throw new RangeError(`Z out of range: ${Z}`);
  const occ = new Map(); // "n,l" -> occupancy
  let remaining = Z;
  for (const { n, l } of MADELUNG) {
    if (remaining <= 0) break;
    const fill = Math.min(SUBSHELL_CAPACITY[l], remaining);
    occ.set(`${n},${l}`, fill);
    remaining -= fill;
  }
  if (applyAnomalies && ANOMALIES[Z]) {
    for (const [key, value] of Object.entries(ANOMALIES[Z])) {
      if (value === 0) occ.delete(key);
      else occ.set(key, value);
    }
  }
  const config = [];
  for (const [key, occupancy] of occ) {
    if (occupancy <= 0) continue;
    const [n, l] = key.split(',').map(Number);
    config.push({ n, l, occupancy });
  }
  config.sort((a, b) => a.n - b.n || a.l - b.l);
  return config;
}

/** Human-readable spectroscopic string, e.g. "1s2 2s2 2p6 3s2 3p6 4s2 3d6" (filling order). */
export function configurationString(Z, options) {
  const config = electronConfiguration(Z, options);
  // Present in Madelung filling order for readability.
  const order = new Map(MADELUNG.map((s, i) => [`${s.n},${s.l}`, i]));
  return [...config]
    .sort((a, b) => (order.get(`${a.n},${a.l}`) ?? 99) - (order.get(`${b.n},${b.l}`) ?? 99))
    .map((s) => `${s.n}${L_LABEL[s.l]}${s.occupancy}`)
    .join(' ');
}

/** Total electron count of a configuration (sanity: equals Z). */
export function configurationElectronCount(config) {
  return config.reduce((sum, s) => sum + s.occupancy, 0);
}
