import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const iccRoot = process.env.ICC_ROOT || '/home/cos/projects/infinite_context_coder';
const python = process.env.PYTHON || 'python3';
const iccTool = process.env.ICC_TOOL || resolve(iccRoot, 'scripts/codebase_tool.py');
const repoName = process.env.ICC_REPO || 'ulg';
const iccDir = resolve(repoRoot, '.icc');
const defaultSkipDirs = [
  '.git',
  'coverage',
  'dist',
  'docs',
  'node_modules',
  'playwright-report',
  'public',
  'test-results'
];
const skipDirs = (process.env.ICC_SKIP_DIRS || defaultSkipDirs.join(','))
  .split(/[,\s]+/)
  .map((entry) => entry.trim())
  .filter(Boolean);

function runIcc(args, { cwd = iccRoot } = {}) {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(python, [iccTool, ...args], {
      cwd,
      env: {
        ...process.env,
        EMSDK_QUIET: process.env.EMSDK_QUIET || '1'
      },
      stdio: ['ignore', 'pipe', 'pipe']
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('error', rejectPromise);
    child.on('close', (code) => {
      if (code === 0) {
        resolvePromise({ stdout, stderr });
        return;
      }
      rejectPromise(new Error([
        `ICC command failed (${code}): ${python} ${iccTool} ${args.join(' ')}`,
        stderr.trim(),
        stdout.trim()
      ].filter(Boolean).join('\n')));
    });
  });
}

function parseJsonOutput(stdout) {
  const start = stdout.indexOf('{');
  const end = stdout.lastIndexOf('}');
  if (start < 0 || end < start) {
    throw new Error(`ICC command did not emit a JSON object:\n${stdout}`);
  }
  return JSON.parse(stdout.slice(start, end + 1));
}

async function main() {
  await mkdir(iccDir, { recursive: true });

  console.log(`Registering ICC repo ${repoName}`);
  await runIcc([
    'register',
    '--name',
    repoName,
    '--path',
    repoRoot,
    ...skipDirs.flatMap((skipDir) => ['--skip-dir', skipDir])
  ]);

  console.log(`Refreshing ICC index for ${repoName}`);
  const index = parseJsonOutput((await runIcc(['index', '--repo', repoName])).stdout);

  console.log(`Refreshing ICC memory for ${repoName}`);
  const memory = parseJsonOutput((await runIcc(['build-memory', '--repo', repoName])).stdout);

  console.log(`Capturing ICC status for ${repoName}`);
  const status = parseJsonOutput((await runIcc(['status', '--repo', repoName, '--check-staleness'])).stdout);
  await writeFile(
    resolve(iccDir, 'ulg_status.json'),
    `${JSON.stringify({
      generatedAt: new Date().toISOString(),
      repo: repoName,
      status
    }, null, 2)}\n`
  );

  console.log(`Capturing ICC architecture summary for ${repoName}`);
  const architecture = parseJsonOutput((await runIcc([
    'architecture-summary',
    '--repo',
    repoName,
    '--bundle',
    '--include-cheatsheet'
  ])).stdout);
  const content = architecture.content || JSON.stringify(architecture, null, 2);
  await writeFile(
    resolve(iccDir, 'ulg_arch_summary.md'),
    [
      '<!-- Generated by npm run icc:update. Do not hand-edit this snapshot. -->',
      '',
      content.trim(),
      ''
    ].join('\n')
  );

  console.log(JSON.stringify({
    ok: true,
    repo: repoName,
    skipDirs,
    indexedFiles: index.result?.files_indexed ?? null,
    memoryChunks: memory.result?.chunks ?? null,
    statusPath: '.icc/ulg_status.json',
    architecturePath: '.icc/ulg_arch_summary.md'
  }, null, 2));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
